//! JSON Schema registry for front matter, per entity type.
//!
//! The schema is generated by `schemars` from in-crate types. The output is
//! exposed via [`schema_for_type`] and serves as the canonical "what the
//! YAML block should look like" surface. Per-entity-type validation runs
//! in [`crate::graph::StoryGraph::validate`] against this registry.

use schemars::{schema_for, JsonSchema};
use serde::{Deserialize, Serialize};

use crate::entity::EntityType;

/// The front-matter shape used as the JSON-Schema source of truth.
///
/// We don't actually deserialize into this on load — `ParsedEntity` keeps
/// `serde_yaml::Value` so the body can carry anything. The schema here is
/// the canonical "what the YAML block should look like" view, generated at
/// compile time and queried at validate time.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct FrontMatterShape {
    /// Globally unique id within the story.
    pub id: String,
    /// Entity type discriminator.
    #[serde(rename = "type")]
    pub type_: EntityType,
    /// Slug matching the on-disk path.
    pub slug: String,
    /// ISO-8601 timestamp.
    pub created_at: String,
    /// ISO-8601 timestamp.
    pub updated_at: String,
}

/// Returns the JSON Schema for the front matter of a given entity type.
///
/// All entity types share the same shape at the front-matter level — the
/// per-type variation lives in the body. This is intentional: we want a
/// single schema for the metadata and free-form Markdown for content.
pub fn schema_for_type(_ty: EntityType) -> schemars::schema::RootSchema {
    schema_for!(FrontMatterShape)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_is_nonempty_for_each_type() {
        for ty in [
            EntityType::Story,
            EntityType::Bible,
            EntityType::Character,
            EntityType::Environment,
            EntityType::Prop,
            EntityType::Chapter,
            EntityType::Scene,
            EntityType::Shot,
        ] {
            let s = schema_for_type(ty);
            let json = serde_json::to_string(&s).unwrap();
            assert!(!json.is_empty(), "{ty:?}");
            assert!(json.contains("FrontMatterShape"), "{ty:?}");
        }
    }
}