//! Action definitions for sagaline-ui.
//!
//! All actions are payload-bearing structs except [`OpenStory`] /
//! [`ReloadStory`], which are unit actions generated by the
//! [`gpui_kit::actions!`] macro. The action wiring lives in
//! [`crate::view::register_actions`]; this module only declares the
//! types so other modules can name them.
//!
//! ## Action naming
//!
//! `SwitchTab` carries the target right-pane tab index. We use a
//! numeric index (rather than a typed enum) because the
//! `Deserialize` derive on `Action` does not accept non-primitive
//! enum payloads cleanly across the `serde_json` boundary the
//! keymap / programmatic dispatch path use. The view layer maps
//! the index back to [`crate::view::RightTab`] on receipt.

use gpui_kit::Action;
use serde::Deserialize;

/// Switch the right pane to a different tab. `tab` is the
/// zero-indexed position of the target tab in the right-pane tab
/// bar (`0` = Preview, `1` = Activity, `2` = Keys).
#[derive(Clone, Action, PartialEq, Eq, Deserialize)]
#[action(namespace = ui, no_json)]
pub struct SwitchTab {
    pub tab: u32,
}

/// Import a provider API key from a file on disk. The user pastes
/// the plaintext into a file and selects it through the file
/// picker; the file's contents are read, trimmed, then encrypted
/// and persisted via [`sagaline_keys::KeyStore::put`].
///
/// `provider` and `key_id` together identify the
/// [`sagaline_keys::ProviderKeyId`] under which the key is stored.
#[derive(Clone, Action, PartialEq, Eq, Deserialize)]
#[action(namespace = ui, no_json)]
pub struct ImportProviderKeyFromFile {
    pub provider: String,
    pub key_id: String,
}

/// Delete a stored provider API key. No confirmation step — the
/// plaintext is gone after this, by design. The user can re-import
/// later.
#[derive(Clone, Action, PartialEq, Eq, Deserialize)]
#[action(namespace = ui, no_json)]
pub struct DeleteProviderKey {
    pub provider: String,
    pub key_id: String,
}

gpui_kit::actions!(sagaline, [OpenStory, ReloadStory]);